name = "neokomik-api"
main = "functions/_worker.js"
compatibility_date = "2024-05-20"
pages_build_output = "./public"

[vars]
# Variabel yang dapat digunakan di Pages Function (sesi/cookie)
JWT_SECRET = "GANTI_DENGAN_STRING_ACAK_PANJANG_DAN_AMAN"
COOKIE_SECRET = "GANTI_DENGAN_STRING_ACAK_LAINNYA"

# Database D1 Anda
[[d1_databases]]
binding = "neokomik_db"
database_name = "neokomik_db"
database_id = "[ID_D1_ANDA]" # Ganti setelah membuat D1
